### ISSUE TITLE
使用带有查询参数的请求无法匹配策略的问题

### ISSUE THREAD

**Issue by CheaterScript** [klren0312/egg-zrole#19]
我看中间件里使用的ctx.originalUrl作为Path用来匹配，Url带有查询参数的情况下会出现无法匹配的问题，能否添加定制化的配置或去掉参数部分。
无法匹配的示例：
Policy
```
p, alice, /alice_data, GET
```
Request
```
alice,/alice_data?a=1,GET
```

**Comment by klren0312** [comment]
ok 我看看 忘了watch项目了...

**Comment by klren0312** [comment]
> 我看中间件里使用的ctx.originalUrl作为Path用来匹配，Url带有查询参数的情况下会出现无法匹配的问题，能否添加定制化的配置或去掉参数部分。 无法匹配的示例： Policy
> 
> ```
> p, alice, /alice_data, GET
> ```
> 
> Request
> 
> ```
> alice,/alice_data?a=1,GET
> ```

我认为这不是中间件干的事 而是你需要在你的model里配置函数来匹配
https://casbin.org/docs/zh-CN/function#matchers%E4%B8%AD%E7%9A%84%E5%87%BD%E6%95%B0

例如使用`keyMatch5` https://github.com/casbin/casbin/pull/910

**Comment by klren0312** [comment]
https://github.com/casbin/node-casbin/issues/357
