### ISSUE TITLE
请不要主动加载中间件

### ISSUE THREAD

**Issue by webignorant** [klren0312/egg-zrole#5]
app.js
```js
config.appMiddleware.unshift(MIDDLEWARE_NAME);
```
自动加载中间件一时爽，无法优雅处理getUser的数据来源要哭人。
一般项目都会提供auth中间件去验证用户身份与提取用户信息到ctx.state.
而egg-zrole默认顶置在中间件最前面，让人情何以堪...
为了设置一个Subject也够折腾了...

**Comment by webignorant** [comment]
补上，参考egg-jwt，考虑不需要鉴权的路由，考虑加入ts的注释支持

**Comment by klren0312** [comment]
感谢建议
