### ISSUE TITLE
考虑支持mutilRole的场景

### ISSUE THREAD

**Issue by webignorant** [klren0312/egg-zrole#6]
某些后台系统，指定用户会存在多种role的场景。
由于管理员不可控，Subject的定义更多考虑是roleName.
因此当前中间件应该扩展一下...

```js
// 原逻辑
const authzorizer = await ctx.app.zrole.enforce(user, path, method);

// 支持多角色验证
let authzorizer;
if (!Array.isArray(user)) {
  user = [ user ];
}
for (const theUser of user) {
  authzorizer = await ctx.app.casbin.enforce(theUser, path, method);
  if (authzorizer) {
    break;
  }
}
```

**Comment by webignorant** [comment]
@klren0312 额外感谢中间件提供的处理思路，不过目前中间件还不符合我需要的场景。
所以我直接拿出来改造了，最终得实现数据库管理所有的角色和配置角色所拥有的权限...

**Comment by webignorant** [comment]
建议中间件加入超级管理员的设定，通过配置提供角色的数组。避免超级管理员的行为还得走casbin的验证。

**Comment by klren0312** [comment]
可以 谢谢思路  大佬是专业的... 我在操作ps 没有后端实操经验

**Comment by klren0312** [comment]
> 建议中间件加入超级管理员的设定，通过配置提供角色的数组。避免超级管理员的行为还得走casbin的验证。

你觉得超级管理员是固定名称好还是可以设置
